# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Scan a binary TransCAD File
#' 
#' This is a C++ implementation written by Amar Sarvepalli and adapted for Rcpp
#' by Greg Macfarlane.
#' 
#' @param bin_file string with the path to the .bin file.
#' @param name character vector of each variable.
#' @param type CharacterVector with the information type for each variable.
#' @param start NumericVector with the number of bytes in which the variable
#'   starts.
#' @param width NumericVector with the number of bytes given for a variable.
#' @param row_length int showing the number of bytes in a row.
#' 
#' @details All input parameter values are available in the \code{.DCB} file 
#'   read by \link{read_dcb}. This is an internal function and should not
#'   normally be used independent of \link{read_tcad_bin}.
#' 
#' @return characters in each element of the vector
#' 
get_df_from_binary <- function(bin_file, name, type, start, width, row_length) {
    .Call('tcadr_get_df_from_binary', PACKAGE = 'tcadr', bin_file, name, type, start, width, row_length)
}

#' @title get columns
#' @name getColumns
#' @details To get number of dataframe columns
#' @param df DataFrame object
#' @return ncols number of columns
#'
getColumns <- function(df) {
    .Call('tcadr_getColumns', PACKAGE = 'tcadr', df)
}

#' @title get rows
#' @name getRows
#' @details To get number of dataframe rows
#' @param df DataFrame object
#' @return nrows number of rows
#'
getRows <- function(df) {
    .Call('tcadr_getRows', PACKAGE = 'tcadr', df)
}

#' @title get dimensions
#' @name getDims
#' @param df DataFrame object
#' @details To get number of dataframe dimensions
#' @return nrowcol array of rows and columns (r x c)
#'
getDims <- function(df) {
    .Call('tcadr_getDims', PACKAGE = 'tcadr', df)
}

#' @title get field names
#' @name getNames
#' @param df DataFrame object
#' @details Method to extract dataframe column names
#' @return names field names
#'
getNames <- function(df) {
    .Call('tcadr_getNames', PACKAGE = 'tcadr', df)
}

#' @title get field width
#' @name get_width
#' @details Method to get column width
#' @param s character field
#' @return element_width width of the column
#'
get_width <- function(s) {
    .Call('tcadr_get_width', PACKAGE = 'tcadr', s)
}

#' @title parse line by comma deliminated
#' @name name_split
#' @details splits line by ","
#' @param line string line separated by delimiter
#' @param delim delimter can be anything
#' @return fields elements of string line
#'
name_split <- function(line, delim) {
    .Call('tcadr_name_split', PACKAGE = 'tcadr', line, delim)
}

#' @title write dictionary file
#' @name write_dcb
#' @param df DataFrame object
#' @param file_name name of the file
#' @details internal function dcb info 
#' @details doesn't return anything
#'
write_dcb <- function(df, file_name) {
    invisible(.Call('tcadr_write_dcb', PACKAGE = 'tcadr', df, file_name))
}

#' @title write binary file
#' @name write_df_to_binary
#' @param df DataFrame object
#' @param file_name output filename
#' @param field_types datatypes
#' @details Method to export data from dataframe to binary file. 
#' @details This exports only 3 datatypes: Character, Integer and Double 
#' @details Writes the *.dcb file along with *.bin file
#' @return new_dcb_info_df prints dictionary file to console
#'
write_df_to_binary <- function(df, file_name, field_types) {
    .Call('tcadr_write_df_to_binary', PACKAGE = 'tcadr', df, file_name, field_types)
}

